# Correlation and bivariate regression  {#sec-t6}


## Learning outcomes {#sec-t6ILO}

After viewing the tutorial materials and following along with the demonstration, you can:

1. Compute and interpret (partial) correlations
2. Set up, run and interpret simple (bivariate) linear regression

## Datasets {#sec-t6data}

This demonstration uses the datasets [**exam_anxiety**](data/exam_anxiety.jasp) and [**album_sales**](data/album_sales.jasp) which were prepared by Andy Field and included in Field, van Doorn and Wagenmakers [-@field2025]. 

**exam_anxiety** contains (fictional) data measuring the variables `Time Spent Revising`, `Exam Performance` (%), `Exam Anxiety` and `Sex` (female/male).

**album_sales** contains (fictional) information on album sales for different bands. The variables are `Adverts` (Advertising budget in thousands of GBP), `Sales` (Album sales in units of thousands), `Airplay` (Number of plays on the radio) and `Image` (Band's image rating from 0-10). 

## Videos {#sec-t6vid}

Coming soon...