---
title: "SRMP: assignment 1"
format: html
---

## Part 1/2 (JASP)

Open **Assignment1_data**. These are (simulated) data from an experiment measuring emotional and nociceptive responses to different types of music. Participants were randomly assigned to one of three conditions (`Music`): listening to 15 minutes of a selection of music from either the Beatles, the Rolling Stones, or U2. After the listening period, participants were asked if they had a headache (`Headache`; Yes/No) and they were also asked to rate how nauseuous they felt on a scale of 0-100 (`Queasy`). The researchers expected that `Music` (IV) would have an effect on these two DVs. <b> *Take a good look at the data file before you begin answering the questions!* </b>

1. Use an appropriate **descriptive/graphical** technique to visualize the impact of `Music` condition on `Headache` (include this in your report) and interpret the output. (**3 points**)
2. Use a suitable **inferential** technique to test for effects. Report the relevant output and offer your conclusions. (**3 points**)
3. Now, consider the `Queasy` data. Visualize these and give a preliminary interpretation. (**3 points**) 
4. Run an appropriate **inferential** statistical test, report all relevant output, and offer your conclusions on the effects of `Music` on `Queasy`. (**4 points**)

## Part 2/2 (conceptual)

Dr. Metheny is interested in whether regularly listening to smooth jazz music can reduce exam stress. A week before an exam, he randomly assigns student participants 
to a nightly listening programme of smooth jazz, or a control condition where they simply follow their established study habits. The dependent variable is the **difference between pre-study exam stress and exam stress reported on the morning of the exam**, with stress originally measured on a 0 – 100 scale (pre- minus post-, meaning 
positive difference scores = stress reduction relative to baseline). Metheny finds a significant reduction (p <.05) and reports that listening to smooth jazz music can reduce study 
stress.

5. What is the most obvious problem you can find in Metheny's conclusion? (**2 points**)
6. How would you address this problem in a replication study? (**2 points**)
  
