---
title: "SRMP: assignment 2"
format: html
bibliography: SRMP_Week1Assignment.bib
csl: apa-annotated-bibliography.csl
---

## Part 1/2 (JASP)

Open **Assignment2_data**. The data file is taken from a study by Attanasio et al. [-@Attanasio2015] on microcredit in Mongolia. Attanasio runs many field experiments on questions that are relevant for economic development and poverty reduction, especially in developing countries. In this particular study, the researchers were interested in comparing the effects of two microfinance approaches that were specifically targeted at women: individual loans and group loans. Group loans involve giving loans not to individual borrowers, but to groups whose members vouch for each other. Forty Mongolian villages, and a total of 1,148 economically disadvantaged women, participated in this field experiment. The experiment was conducted in collaboration with a Mongolian bank, XacBank. Villages were randomly assigned to one of three conditions: access to group loans, access to individual loans or no loans. One of the goals of the study was to examine whether access to group loans resulted in more lending.

The assignment file contains a reduced and edited version of the raw data set. The original data was collected at the level of households but to make things a little simpler, we have combined it so that you have just one case for each village. Where the original data expressed the amounts borrowed in Mongolian tögrög, we have converted the amount to *thousands of tögrög*. <b> *Take a good look at the data file before you begin answering the questions!* </b>

**Before proceeding to the questions, compute a new variable** named `total_amount_borrowed_XacBank` that indicates how much money residents of each village borrowed from XacBank across their first three loans from the bank. Then, combine this value with the `total_amount_borrowed_nonXacBank` variable – which indicates how much the residents borrowed from other banks – into a variable `Grandtotal_amount_borrowed`. Ensure that you label your variables correctly! 

1. Examine `Grandtotal_amount_borrowed` with the **Descriptives** option. Choose the **most appropriate measures** for central tendency and dispersion, and report these in text. (**2 points**) 
2. Create boxplots for the `Grandtotal_amount_borrowed` variable, separated by treatment condition, and paste these into your assignment document. Report the **casenumber** and the **soum** number of any outlier(s).  (**2 points**)
3. For the `Grandtotal_amount_borrowed` variable, in each of the treatment conditions, report on whether the data satisfy the assumption of normality and state how you reached your conclusions. (**2 points**)
4. Give your impressions on whether the assumption of homogeneity of variances holds between the three treatment conditions on the `Grandtotal_amount_borrowed` variable and state your reasoning. (**2 points**) 
5. Visualise the `total_amount_borrowed_XacBank` and the amount borrowed from other sources (`total_amount_borrowed_nonXacBank`), per treatment group and paste your graph into your submission. Discuss the pattern of results **based only on what you see in your graphs (i.e., don't run any inferential tests)**. (**2 points**)

## Part 2/2 (conceptual)

Dr de Lange is studying the effect of candidate height in elections. She formulates the hypothesis that tall candidates are more likely to be elected than candidates with relatively low height. She performs a laboratory experiment with two conditions. Participants are randomly assigned to either the low height condition, which presents a fictional candidate who is of relatively low height, or the tall height condition, which presents a fictional candidate who is relatively tall. After being presented with the candidate, subjects are asked how likely it is that they would vote for the candidate in a general election.

6. What are the null and the alternative hypotheses Dr. de Lange’s study? (**1 point**)
7. What is the level of measurement of the IV in Dr de Lange’s study? (**1 point**)
8. Dr. de Lange finds that voting intention is higher for taller candidates than for shorter candidates (p = .034). 
    a. How should you interpret the p-value that Dr. de Lange has reported (assuming α = .05)? (**1 point**) 
    b. State what it says about the null and about the alternative hypothesis. (**1 point**)
9. Assume that Dr. de Lange planned to have 80% power in her study. 
    a. Explain what this means. (**1 point**) 
    b. Would the power of her study have been different if she had chosen α = .01? Explain why (not). (**1 point**)

<br>


## References

