---
title: "SRMP: answers for assignment 6"
format: html
bibliography: SRMP_Week5Exercise.bib
csl: apa-annotated-bibliography.csl
---

## Part 1/2 (JASP)

Open **Assignment6_data**. These come from a large study [@Smith2017] which tested whether 'moral foundations' [@HaidtCraig] can be linked to political ideology. Australian subjects filled in a 20 item questionnaire on their 'moral foundations' (with four items per dimension, e.g. 'Compassion for those who are suffering is the most crucial virtue'; six-point Likert scale, 0 = 'strongly disagree', 5 = 'strongly agree'). 'Moral foundation' variables start with the letters MF and at the end of their labels they have a letter denoting to which dimension they belong (c = Care/Harm, f = Fairness/Cheating, l = Loyalty/Betrayal, a = Authority/Subversion, d = Disgust/Purity).

Consider the five aggregated 'moral foundations' variables: `Care`, `Fairness`, `Loyalty`, `Authority`, and `Purity`. These variables are also already summed in their according dimension, such that the higher the score, the more a participant found the moral dimension important/relevant. Imagine that you hypothesize that scores on these variables are predicted by political ideology (`IDEO` ranging from 1 - very liberal - to 3 - very conservative), age (`AGE`) and sex (`SEX`).

1.  Fit models to test for the effects of `IDEO`, `Age` and `Sex` on **each of the aggregated 'moral foundations' variables** and interpret the findings. Note that you do **not** have to use APA format, but you should give information about the direction, significance and meaning of all effects tested. (**9 points**) <span style="color: red;">
    -   `IDEO` significantly predicts all variables, with negative effects on `Care` and `Fairness`, and positive effects on the rest. In other words, a more liberal ideology predicts a higher importance of `Care` and `Fairness`, while a more conservative ideology predicts a higher importance of `Authority`, `Loyalty` and `Purity`. (3)
    -   `AGE` significantly and positively predicts all variables. Older participants tend to value the moral dimensions more than younger participants.  (3)
    -   `SEX` significantly predicts all variables except `Authority`: females value `Care`, `Fairness` and `Purity` more than males, while males value `Loyalty` more than females. (3) </span>

## Part 2/2 (Conceptual)

2.  Consider all of the assumptions of the modelling technique you used in the previous section. For <b><i>one</i></b> of the independent variables, checking for <b><i>one</i></b> of these assumptions would be redundant. Explain why it is not important to check this assumption with respect to the variable in question. (**3 points**) <span style="color: red;">
    -   It is not necessary to check the assumption of linearity (1) for the `SEX` (1) variable as it is only represented by two categories in the dataset. This means that the relationship between `SEX` and the moral foundations variables cannot be modelled by anything more complex than a straight line/linear model (1).</span>
3.  A colleague suggests you think carefully about the inclusion of `Age` in your models. Why might they be concerned about this? (**2 points**) <span style="color: red;">
    -   `Age` and `IDEO` might be correlated (1) which could introduce collinearity (1) into the model </span>
4.  Yet another colleague expresses concern about the type-I error rate of your approach. What might underlie their concerns, and what might you do to address them? (**3 points**) <span style="color: red;">
    -   Type-I errors occur when $H_0$ is incorrectly rejected, and the chances of committing such an error increase when performing multiple hypothesis tests on related data (1) - the familywise error rate (FWE). As we run five different regression models based on data from the same participants, our chances of committing a type-I error - reporting a false positive - increase. (1)
    -   Applying an adjustment to the $\alpha$ level (e.g, Bonferonni correction) we use for the five models could address the issue. (1) </span>

## References
